### ISSUE TITLE
npm start does not work to start the bot

### ISSUE THREAD

**Issue by Shhwip** [kabobrocks/kabob-bot#7]
In the read me it says "5. In terminal, go to the root folder of the project and type in "npm start" to start the bot"

That doesnt work. I instead use 
node app.js to start the bot

**Comment by kabobrocks** [comment]
https://github.com/kabobrocks/kabob-bot/commit/a8318d316f1acad2d78b73eb02f6319380bdf016

**Comment by Shhwip** [comment]
still doesnt work
